{% set name = "kaldi_io" %}
{% set version = "0.9.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kaldi_io-{{ version }}.tar.gz
  sha256: 48f8057413e8800a18518e2077f1d29a40b9487b80052a496828a68817aa93dc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.15.3
    - python >={{ python_min }}

test:
  imports:
    - kaldi_io
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vesis84/kaldi-io-for-python
  summary: Glue code connecting Kaldi data and Python.
  license_file: LICENSE
  license: Apache-2.0

extra:
  recipe-maintainers:
    - thewchan
